### PR TITLE
change the akka version to 2.3.5 to fix the no such method issue

### PR DESCRIPTION
**Pull request by jerrybai2009**
We met the no such method issue on akka-actor version 2.3.15, change the version to 2.3.5 to fix it

### CODE REVIEW

**Comment by ericsun2** [comment]
I think it should be 2.2.5

**Comment by rkluszczynski** [comment]
@jerrybai2009, @ericsun2 : We had the same problem after this update of dependency. I have change it to version 2.2.0, because this is the version which play 2.2.4 has. 

Don't you think that it is better to use the same version as play framework?

Kind regards,
Rafal

**Comment by ericsun2** [comment]
I think the akka version should be 2.2.5

**Comment by rkluszczynski** [comment]
@ericsun2 I did a bit of thinking and based on semantic version interpretation you are rather right:) This should be the latest version of 2.2.x (in classpath probably both versions will be available so who knows which one will be used :-) ).

By the way: we like new web outfit;) Nice job 👍

**Comment by jerrybai2009** [comment]
It should be 2.2.5.

Thanks!

**Pull request merged**
