### PR TITLE
Docker Support

### PR DESCRIPTION
**Pull request by msknapp**
Added docker build directories for WhereHows.

### CODE REVIEW

**Comment by mars-lan** [comment]
Thanks for the contribution! 

A few general comments
1. You may wish to use the [deployment instruction](https://github.com/linkedin/WhereHows/wiki/Getting-Started#deploying-the-web-application-server) for building the tarballs for the docker image, instead of zipping the entire web & backend-service directories.
2. If you use the tarball from 1, you can run the service directly using the starting script, instead of relying on activator, which would simplify your docker image
3. Don't think the ivy update is necessary if u use the tarball from 1.

**Comment by mars-lan** [comment]
@msknapp happy to merge the PR in if you could address the comments.

**Comment by msknapp** [comment]
sorry I have not responded in a while.  

I think that your instructions are not very clear, especially for people not familiar with gradle like me.  I think I figured out now, that './gradlew dist' is generating a distributable, standalone archive of the application.  That fact is certainly not clear from your documentation, because the section is titled "Deploy".  

If that was clear from the start, it probably would have saved me a day or more of work, and we would not be in the situation we are in now.  I think the instructions need to be updated, to encourage people to use a pre-built distribution instead of building from source, and running with activator.  Specifically, naming a section "Deploy" does not give me the impression that we are building a standalone executable archive of the application.  It's a bit misleading.

Unfortunately I have a lot on my to-do list right now and I'm not sure when I will have time to make the requested fixes.  Hopefully within the next two weeks.

**Comment by msknapp** [comment]
I am trying this again, but right now WhereHows is not building for me, I keep getting this:
:web:playClean
java.io.FileNotFoundException: /..../workspace/WhereHows/web/project/project/target/config-classes/$5553d4661b1f096fecce.cache (No such file or directory)

**Comment by mars-lan** [comment]
Could you try manually remove the "target" directory and try again? Activator is a huge PITA and we're currently working moving away from it altogether

**Comment by msknapp** [comment]
Please close/reject this pull request.  I decided it would be easier to just create a new pull request so the git logs will be cleaner.

**Pull request closed without merging**
