### PR TITLE
implement the list view for dataset and flow

### PR DESCRIPTION
**Pull request by jerrybai2009**
Wherehows supports ListView and TreeView for dataset and flow browsing.
TreeView provides the view of whole hierarchy of datasets, the ListView only provides one level of dataset nodes. User can click the node to go to next level, and click the link in breadcrumb which is on right top of page to go back to higher level.
  
See attached scrrenshot:
image

### CODE REVIEW

**Comment by ericsun2** [comment]
The navigation UI is more efficient. Please enhance the "Filter By" for the Fancytree part in the next sprint:
- found matches in children node
- hide nodes w/o match

The pull request LGTM

**Comment by jerrybai2009** [comment]
Filter By is implemented, and for Fancytree, we set the filter mode to "dimm" instead of "hide".
The unmatched node is grey out.
Please see attached screen shots.
image
image

**Comment by rkluszczynski** [comment]
@jerrybai2009 Hello, short question just to be sure: this filter option and new look works also without elasticsearch, right? 

Kind regards,
Rafal Kluszczynski

**Comment by ericsun2** [comment]
Thanks for the preview and explanation of the color theme.

**Comment by jerrybai2009** [comment]
The ListView and TreeView get the data from mySQL directly.
Only the search and Advanced search hit the elasticsearch server.
The filter by is on client side for loaded data, in other words, filter by does not trigger any rest api call to get data.

**Comment by rkluszczynski** [comment]
@jerrybai2009 Thanks for explanation:)

**Pull request merged**
