### PR TITLE
Add etl job to extract/load druid metadata

### PR DESCRIPTION
**Pull request by wenhuaOpenx**

### CODE REVIEW

**Comment by wenhuaOpenx** [comment]
Sorry for that. I've fixed the build and push the updated code.

**Comment by mars-lan** [comment]
A few more to fix: https://travis-ci.org/linkedin/WhereHows/builds/265775545#L1451

**Comment by mars-lan** [comment]
Please also format your code using this style in IDEA: https://github.com/linkedin/WhereHows/blob/master/wherehows-docs/LinkedIn%20Style.xml

**Comment by wenhuaOpenx** [comment]
hi Mars, I reformat the code based on LinkedIn code style, and fix the build error. Travis CI reports that the build is passed. Please help review my PR, and let me know anything else I missed. Thanks very much for your time! :)

**Comment by wenhuaOpenx** [comment]
Thank you for reviewing, @mars-lan! /wherehows-etl/README.md is updated, I append the description about druid dataset to the end, not sure if I shall move it up, next to "Hive Dataset". Please advise, Thanks!

**Pull request merged**
