### PR TITLE
add metadata-etl contrib module for jdbc and lineage

### PR DESCRIPTION
**Pull request by clojurians-org**
enhance on jdbc schema and lineage module(hive only, oracle later)...

### CODE REVIEW

**Comment by mars-lan** [comment]
Thanks for the contribution! It might take us a bit time to go through this large PR, but for a starter, could you rename your top-level readme file to `README.md` to align with the convention?

**Comment by clojurians-org** [comment]
Thanks, I will do it.
You can give more suggestion as I only write messy simple tool to mix for my personal usage situation.
 I will update them together after finishing parsing Oracle SQL. And refine Hive parser a little.
Basically, I am focusing on sql lineage parser.

**Comment by mars-lan** [comment]
@clojurians-org would you be interested in re-submitting this PR again?

**Comment by clojurians-org** [comment]
okay, i will split to small function to submit step by step in this week.

**Pull request closed without merging**
