### PR TITLE
Possibility to store JSON for tree view in database

### PR DESCRIPTION
**Pull request by rkluszczynski**
Hello, at the moment json for datasets tree view can be read only from a file. This is "no go" for installations where "backend-service" is not on the same machine as "web" service. Unfortunately, our case.

I have prepared PR which stores JSON in database shared between those two services. The idea consist of:
- when configuration key **wherehows.ui.tree.dataset.file** is missing in _wh_property_ table, then job/script **DatasetTreeBuilder.py** stores it in database instead of file,
- **web** module has new configuration option **datasets.tree.source** which can have value _database_ meaning that JSON should be read from database, otherwise (missing option or _file_ value) JSON is read from file like it was so far. 

Could you review my changes?
Would it be possible to include those changes into distribution?

Please let me know in case I'm missing something or some changes have to be made.

Kind regards,
Rafal Kluszczynski

### CODE REVIEW

**Comment by ericsun2** [comment]
Store the tree JSON in db is nice. We also try to move to partial tree generation on-the-fly, because the tree can grow really huge with hundreds of top level objects for hdfs, hive and teradata. Scrolling and try to locate a particular node in the tree can become difficult.

**Comment by rkluszczynski** [comment]
@ericsun2 Yeap, agree about tree view size. So, I understand that probably this PR will be obsolete. Please tell me, when do you plan to change tree view generation?

**Comment by nikhiltanwar** [comment]
If tree view size is huge and it wont fit in column length of RDBMS table then, Elasticsearch might be a better home for it.

**Comment by keremsahin1** [comment]
###  Data Hub Announcement
Thanks for your contribution. We are dropping PR requests for `WhereHows` from now on. Active development for this project will continue on `datahub` branch until it's finally merged to `master`. LinkedIn improved the architecture of `WhereHows` and rebranded `WhereHows` into **Data Hub** recently. Please check the [blog post](https://engineering.linkedin.com/blog/2019/data-hub) to learn more about **Data Hub** and hold on for the first official release which is very soon :)

**Pull request closed without merging**
