### PR TITLE
Fetching dataset watchers userName via get /dataset/watchers

### PR DESCRIPTION
**Pull request by nvemuri1**
These changes brings in support to retrieve userName of the users who are watching the given dataset.

### CODE REVIEW

**Comment by ericsun2** [comment]
@nvemuri1 for some reason you were using an older baseline. The "linkedin" branch is up-to-date, so your pull request ideally should only contains 3 files: (DatasetController.java, UsersDao.java, routes)

The gudusoft.gsqlparser related Travis CI error is due to a specific third party jar. We can ignore this CI error for Travis.

**Comment by ericsun2** [comment]
LGTM

**Comment by nvemuri1** [comment]
I made necessary changes (i think). You should only see 3 files changed now.

**Comment by nvemuri1** [comment]
Who can merge the commit to linkedin/WhereHows?

**Comment by ericsun2** [comment]
Thanks, @nvemuri1 for the contribution. 
LGTM

**Pull request merged**
